# Generated by Django 6.1 on 2026-08-15 09:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الفرع')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الفرع')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='موقع الفرع')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='الشركة', max_length=200, verbose_name='اسم الشركة')),
                ('attendance_time', models.TimeField(default='09:00', verbose_name='ميعاد الحضور')),
                ('backup_enabled', models.BooleanField(default=True, verbose_name='تفعيل النسخ الاحتياطي')),
                ('backup_days', models.IntegerField(default=30, verbose_name='عدد أيام الاحتفاظ بالنسخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'إعدادات الشركة',
                'verbose_name_plural': 'إعدادات الشركة',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر العرض')),
                ('offer_description', models.TextField(blank=True, null=True, verbose_name='وصف العرض')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صورة المنتج')),
                ('is_offer_active', models.BooleanField(default=False, verbose_name='العرض فعال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('employee_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='كود الموظف')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('role', models.CharField(choices=[('ADMIN', 'أدمن'), ('MANAGER', 'مدير'), ('REGIONAL', 'إقليمي'), ('ACCOUNTANT', 'محاسب'), ('CASHIER', 'كاشير'), ('SALES', 'مبيعات')], max_length=50, verbose_name='الصلاحية الوظيفية')),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='النقاط')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='الصورة الشخصية')),
                ('dark_mode', models.BooleanField(default=False, verbose_name='الوضع الليلي')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آخر IP دخول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='core.branch', verbose_name='الفرع')),
                ('managed_branches', models.ManyToManyField(blank=True, related_name='regional_managers', to='core.branch')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفين',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='العملية')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='بيانات المتصفح')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العملية')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل نشاط',
                'verbose_name_plural': 'سجلات النشاط',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('file_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='حجم الملف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النسخة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'نسخة احتياطية',
                'verbose_name_plural': 'النسخ الاحتياطية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_group', models.CharField(blank=True, choices=[('ALL', 'الجميع'), ('ACCOUNTANTS', 'المحاسبين'), ('CASHIERS', 'الكاشير'), ('REGIONALS', 'المديرين الإقليميين'), ('BRANCH_MANAGERS', 'مديري الفروع')], max_length=50, null=True, verbose_name='مجموعة المستلمين')),
                ('subject', models.CharField(max_length=255, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PRICE_UPDATE', 'تحديث سعر'), ('EVALUATION', 'تقييم'), ('REWARD', 'مكافأة'), ('MESSAGE', 'رسالة'), ('ATTENDANCE', 'حضور'), ('SYSTEM', 'النظام')], default='SYSTEM', max_length=50, verbose_name='نوع الإشعار')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت القراءة')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='الرابط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='التاريخ')),
                ('check_in_time', models.TimeField(blank=True, null=True, verbose_name='وقت الحضور')),
                ('check_out_time', models.TimeField(blank=True, null=True, verbose_name='وقت الانصراف')),
                ('check_in_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP الحضور')),
                ('check_out_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP الانصراف')),
                ('late_minutes', models.IntegerField(default=0, verbose_name='دقائق التأخير')),
                ('status', models.CharField(choices=[('PRESENT', 'حاضر'), ('ABSENT', 'غائب'), ('LATE', 'متأخر')], default='PRESENT', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'حضور',
                'verbose_name_plural': 'سجل الحضور',
                'ordering': ['-date', '-check_in_time'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_attendance_per_day')],
            },
        ),
        migrations.CreateModel(
            name='BranchEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='تقييم الموظفين')),
                ('admin_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='تقييم الإدارة')),
                ('total_branch_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='التقييم النهائي للفرع')),
                ('year', models.PositiveIntegerField(default=2026, verbose_name='السنة')),
                ('week_number', models.PositiveIntegerField(default=1, verbose_name='رقم الأسبوع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقييم')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_evaluations', to='core.branch', verbose_name='الفرع')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='المقيم')),
            ],
            options={
                'verbose_name': 'تقييم فرع',
                'verbose_name_plural': 'تقييمات الفروع',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('branch', 'evaluator', 'year', 'week_number'), name='unique_branch_evaluation_per_week'), models.CheckConstraint(condition=models.Q(('admin_score__gte', 0), ('employees_score__gte', 0)), name='branch_scores_not_negative')],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria_dealing', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='التعامل')),
                ('criteria_accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='الدقة')),
                ('criteria_honesty', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='الأمانة')),
                ('criteria_work_quality', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='جودة العمل')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='المجموع النهائي')),
                ('evaluation_type', models.CharField(choices=[('PEER', 'تقييم زملاء'), ('ADMIN', 'تقييم الإدارة'), ('MANAGER', 'تقييم مدير الفرع')], default='PEER', max_length=50, verbose_name='نوع التقييم')),
                ('year', models.PositiveIntegerField(default=2026, verbose_name='السنة')),
                ('week_number', models.PositiveIntegerField(default=1, verbose_name='رقم الأسبوع')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقييم')),
                ('evaluated_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='الموظف المقيم')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='المقيم')),
            ],
            options={
                'verbose_name': 'تقييم موظف',
                'verbose_name_plural': 'تقييمات الموظفين',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('evaluator', 'evaluated_employee', 'year', 'week_number'), name='unique_employee_evaluation_per_week'), models.CheckConstraint(condition=models.Q(('evaluator', models.F('evaluated_employee')), _negated=True), name='prevent_self_employee_evaluation'), models.CheckConstraint(condition=models.Q(('criteria_accuracy__gte', 0), ('criteria_dealing__gte', 0), ('criteria_honesty__gte', 0), ('criteria_work_quality__gte', 0)), name='evaluation_scores_not_negative')],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2026, verbose_name='السنة')),
                ('week_number', models.PositiveIntegerField(verbose_name='رقم الأسبوع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قيمة المكافأة')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ المكافأة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'مكافأة',
                'verbose_name_plural': 'المكافآت',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'year', 'week_number'), name='unique_user_reward_per_week')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2026, verbose_name='السنة')),
                ('week_number', models.PositiveIntegerField(verbose_name='رقم الأسبوع')),
                ('rank_position', models.PositiveIntegerField(verbose_name='الترتيب')),
                ('reward_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة المكافأة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_rankings', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'ترتيب أسبوعي',
                'verbose_name_plural': 'الترتيبات الأسبوعية',
                'ordering': ['year', 'week_number', 'rank_position'],
                'constraints': [models.UniqueConstraint(fields=('user', 'year', 'week_number'), name='unique_user_weekly_ranking'), models.UniqueConstraint(fields=('year', 'week_number', 'rank_position'), name='unique_weekly_rank_position')],
            },
        ),
    ]
